### ISSUE TITLE
Тема статті в журналі

### ISSUE THREAD

**Issue by IlonaSofianidi** [IlonaSofianidi/commandWork#1]
Про що буде наш новий випуск в журналі ?

**Comment by NataliaYur** [comment]
і тут ми поговоримо про Ліху сміху :)
Як вам нові команди?

**Comment by NataliaYur** [comment]
Давай поговоримо про Лігу сміху)

**Comment by IlonaSofianidi** [comment]
@NataliaYur Гарна ідея

**Comment by zhemelko8** [comment]
давайте обговорювати щось життєве)

**Comment by zhemelko8** [comment]
а давайте висвітлимо тему чогось соціального - наприклад опитування кава чи чай?

**Comment by IlonaSofianidi** [comment]
О, кава чи чай - взагалі круто!

**Comment by IlonaSofianidi** [comment]
Теж непогана

**Comment by zhemelko8** [comment]
@NataliaYur @IlonaSofianidi давайте створимо тему статті нашого журналу на цю тему)

**Comment by IlonaSofianidi** [comment]
@zhemelko8 пропоную просто різні рубрики зробити
