### ISSUE TITLE
Потренувати створення теми для обговорення та власне самого обговорення

### ISSUE THREAD

**Issue by zhemelko8** [IlonaSofianidi/commandWork#11]
З цим проблем я думаю не має, тем у нас багато вийшло

**Comment by IlonaSofianidi** [comment]
Та я думаю ,можна сміливо це issue закривати ,бо ми вже скільки обговорень створили )Що вже добре натренирувалися 
так @NataliaYur ?

**Comment by NataliaYur** [comment]
@IlonaSofianidi хах так) :smiley:
