### ISSUE TITLE
Зміст журналу

### ISSUE THREAD

**Issue by NataliaYur** [IlonaSofianidi/commandWork#13]
@IlonaSofianidi @zhemelko8 дівчата, як думаєте тем достатньо для нашого першого видання журналу?)

**Comment by zhemelko8** [comment]
хаха я думаю для першого журналу достатньо

**Comment by IlonaSofianidi** [comment]
Думаю так.Для одного випуску більше ніж достатньо

**Comment by NataliaYur** [comment]
:ok_hand:  тоді готуємося до випуску, і закриваємо це обговорення
