### ISSUE TITLE
Обговорюємо Лігу сміху :)

### ISSUE THREAD

**Issue by NataliaYur** [IlonaSofianidi/commandWork#2]

**Comment by NataliaYur** [comment]
ні, а чому ти так думаєш? @zhemelko8

**Comment by IlonaSofianidi** [comment]
@zhemelko8  Ти натякаєш на Загорецьку Людмилу Степанівну?

**Comment by NataliaYur** [comment]
@IlonaSofianidi хаха, я думаю у них це лише така роль

**Comment by zhemelko8** [comment]
@NataliaYur я думаю однозначно, що у них є певна база знань, і досить потужна база знань.Насправді, жартувати важко. Кмітливість, розуміння ситуації, розуміння , чи доречний буде цей жарт, орієнтування в політичних процесах це важко. От наприклад, візьмемо якусь політичну чи навіть економічну подію - люди, які жартують повинні : по-перше, знати про цю подію ( а зараз суспільство не інтенсивно цікавиться новинами); по-друге, зрозуміти цю подію (реально зрозуміти , з якою структурою вони працюють) ; по-третє, вміти над цим пожартувати. І це важко зробити доречно, смішно і лаконічно.

**Comment by NataliaYur** [comment]
@zhemelko8 все ж погоджуюся, переконала

**Comment by IlonaSofianidi** [comment]
@zhemelko8  чесно кажучи , думала що ти навпаки їх оціниш)) Скажеш що дурний гумор
