### ISSUE TITLE
Кава vs Чай

### ISSUE THREAD

**Issue by zhemelko8** [IlonaSofianidi/commandWork#3]
Що більше любите пити? І якщо ви обираєте два варіанти, то при яких умовах пєте каву , а при яких чай?

**Comment by NataliaYur** [comment]
особисто я більше люблю пити каву, для мене цей напій більше задоволення приносить ніж чай

**Comment by IlonaSofianidi** [comment]
@zhemelko8  так як я не зі Львова , то можу прожити і без кави. А от чай , то вже інша річ

**Comment by NataliaYur** [comment]
Мені от цікаво, чому Львів багатьом асоціюється з кавою?) Так я погоджуюся, що кожна вуличка у Львові буквально кишить кав'ярнями, і запах кави ніби як туман зранку осідає на вулицях, але у нас ж нема кавових плантацій 😆

**Comment by zhemelko8** [comment]
теж цікава тема, цікаво послухати інших, думаю потрібно створити голосування,у нашому журналі задамо інтернет адресу де можна буде пройти певне голосування. Цікавий результат)
