### ISSUE TITLE
 jury of the League of Laughter

### ISSUE THREAD

**Issue by IlonaSofianidi** [IlonaSofianidi/commandWork#4]
Як вам новий склад жюрі ?

**Comment by NataliaYur** [comment]
мені подобається, хоча я навіть не очікувала такого складу журі

**Comment by NataliaYur** [comment]
шось цікаве 👍

**Comment by IlonaSofianidi** [comment]
@zhemelko8 @NataliaYur  чи доцільно обговорювати жюрі в статті?Чи можемо мати проблеми?
