### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by zhemelko8** [IlonaSofianidi/commandWork#5]
А якщо так реально, вам подобається Github? якщо так, то чим?
[https://github.com/](url)

**Comment by IlonaSofianidi** [comment]
@zhemelko8 подобається .Це місце в якому я крок за кроком реалізувати завдання . Подобається що 
 є Project, Issues

**Comment by NataliaYur** [comment]
чесно, спершу я навіть не розуміла для чого це все, коли детальніше розібралася, то сподобалося, оскільки з допомогою GitHub можна реалізовувати проекти спільними зусиллями, групою людей

**Comment by zhemelko8** [comment]
@IlonaSofianidi не знаю скільки відсотків, але можу сказати, що GitHub важлива частина, дуже потужна програма для сучасних розробників, у ній є багато фішок, які можливо не всім відомі, котрі допомагають полегшити роботу. Тому я думаю немалим відсотком користувачів користується GitHub.
