### ISSUE TITLE
Гори чи море?

### ISSUE THREAD

**Issue by NataliaYur** [IlonaSofianidi/commandWork#6]

**Comment by NataliaYur** [comment]
@IlonaSofianidi @zhemelko8 що для вас краще? де ви більше любите відпочивати? :smiley:

**Comment by zhemelko8** [comment]
@NataliaYur ооо люблю на такі теми поговорити

**Comment by zhemelko8** [comment]
гори чи море? 
а якщо гори на морі? :smile:

**Comment by IlonaSofianidi** [comment]
@zhemelko8  ахахах;) Дотепно

**Comment by NataliaYur** [comment]
я думаю винесемо це питання на загальне обговорення, подивимося на думки інших.
