### ISSUE TITLE
Потренувати створення проекту

### ISSUE THREAD

**Issue by IlonaSofianidi** [IlonaSofianidi/commandWork#8]

**Comment by IlonaSofianidi** [comment]
@zhemelko8  ага, скільки часу розбирали ті issue)) Але так

**Comment by NataliaYur** [comment]
я думаю то цього вартує @IlonaSofianidi

**Comment by IlonaSofianidi** [comment]
@NataliaYur  теж так думаю)

**Comment by NataliaYur** [comment]
будемо вміти користуватися GitHubом :+1:

**Comment by zhemelko8** [comment]
Good , тоді переходимо до наступних завдань)
