### ISSUE TITLE
Вибір дати випуску

### ISSUE THREAD

**Issue by IlonaSofianidi** [IlonaSofianidi/commandWork#9]
На яку дату перенесемо наш випуск в журналі ,так як 1 травня вихідний ?

**Comment by zhemelko8** [comment]
можливо 3?

**Comment by IlonaSofianidi** [comment]
Ладно,Можна)close #10

**Comment by IlonaSofianidi** [comment]
Можна ,я кинула список вихідних на майбутнє у файл
